### PR TITLE
Fix #54 java8 branch uses java11

### LINKED ISSUE #54: java8 branch uses java11
Is this intended?

https://github.com/itzg/docker-bungeecord/blob/java8/Dockerfile#L1

### PR DESCRIPTION
**Pull request by thenilsdev**

### CODE REVIEW

**Comment by itzg** [comment]
Thanks for catching this, but it actually needs to be changed to be like

https://github.com/itzg/docker-bungeecord/blob/d7b2f57f88b3264d86705520740027a7b29cd487/Dockerfile

Otherwise, the multi-architecture build fails for arm64 and armv7

**Comment by itzg** [comment]
FYI this is where I broke it

https://github.com/itzg/docker-bungeecord/commit/99bd29a11a09c9ce847dd9dcc6bf44c41b7dc0f7

**Comment by thenilsdev** [comment]
I don't quite understand. 
https://github.com/itzg/docker-bungeecord/blob/d7b2f57f88b3264d86705520740027a7b29cd487/Dockerfile and https://github.com/thenilsdev/docker-bungeecord/blob/java8/Dockerfile differ only in the base image (`ubuntu` -> `adoptopenjdk`) and the removal of `openjdk-8-jre-headless`.

Tested my change and it works, unfortunately I can only test on amd64.

Could you give me feedback on what needs to be changed specifically? I will look into it then

**Comment by itzg** [comment]
I first attempted what you did and the BuildKit multiarch build failed like this

https://github.com/itzg/docker-bungeecord/runs/2370387620?check_suite_focus=true#step:7:42

It was caused by the official adoptopenjdk 8-jre-hotspot lacking manifest entries for arm64 and arm/v7; however I see them there now. Maybe I caught them in between builds. 

https://hub.docker.com/layers/adoptopenjdk/library/adoptopenjdk/8-jre-hotspot/images/sha256-5912a0f4d2e10c91ce26415089e42c1277ca7ae2b7798c60e31ef80a3da70d09?context=explore

I'll take a look at this in a few hours to see if your change will now build multiarch.

**Review by itzg — APPROVED** [review]
Just tested a docker buid locally with `--platform linux/amd64 --platform linux/arm64 --platform linux/arm/v7` and it builds fine now.

**Comment by itzg** [comment]
...and docker pulled and confirmed:

```
> docker run --rm --entrypoint java itzg/bungeecord:java8 -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
```

**Pull request merged**
