### PR TITLE
Bump default Velocity version

### PR DESCRIPTION
**Pull request by repository**
Velocity 1.1.0 has been outdated since last October

### CODE REVIEW

**Review by itzg — APPROVED** [review]
Thanks. I seem to remember theirs was one of those download setups where the script can't auto discover the latest.

**Comment by repository** [comment]
Did a bit of experimenting, turns out https://versions.velocitypowered.com/download/latest.jar is a valid URL

**Comment by itzg** [comment]
Ooh, that would be nice to use. Feel like doing another PR? 😁

**Comment by repository** [comment]
sure #50

**Pull request merged**
